version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password 
    volumes:
      - db-data-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: bw-todo-api:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: example
      DEPLOYMENT_ENV: true
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: bw-todo-frontend:latest
    ports:
      - 4200:80
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      MYSQL_ROOT_PASSWORD: example
volumes:
  db-data-volume:
